---
- name: Create a volume with options
  docker_volume:
    name: volume_on_disk
    driver: local
    driver_options:
      type: none
      device: /data/test
      o: bind
- name: Run my-app docker container
  hosts: localhost.localdomain
  remote_user: root
  tasks:
  - name: Create Container
    docker_container:
      name: my-app
      image: my-app:latest
      state: started
      volumes:
      - volume_on_disk:/app